- get-charms
- publish-charms
- push-and-publish
- push-and-publish-multi-series
Merge dev branch (charm pusher changes) into master.
The dev branch is what OSCI has been running on for ~10 days.  Once merged, we will flip it back to consume release-tools @ master.
> Merge dev branch (charm pusher changes) into master.

- commit-message-amulet-defs-1609.txt
- update-amulet-defs-16.09
Add update-amulet-defs script
While this is specific to 16.10 pre-release tasks, proposing it to the repo as a baseline example to roll forward with as needed for similar operations.
> Amulet def updater

- README.md
- build-charm
- generate-repo-info
- grant-bot-write
- push-and-release
- release-stable-charms
- https://bugs.launchpad.net/charm-test-infra/+bug/1647000
- https://bugs.launchpad.net/charm-test-infra/+bug/1654000
- https://github.com/juju/charmstore-client/issues/104
- https://github.com/juju/docs/issues/1555
> Update build and push to address stable charm tool syntax change

- bug-link-overrides.txt
- charms.txt
- push-and-release
Update new charms for 17.02 Release
> Update new charms for 17.02 Release

- .gitignore
- charms.txt
- py3-charms.txt
- source-charms.txt
* Remove ODL from charm lists, regarding deprecation
* Add new charm projects
* Update charm helper sync files
> Updates for 18.11

- .gitreview
- stable-branch-updates
Update the bundles to use stable charms.
> Update zaza charms for stable branches

- build-charm
This reverts commit be472c0dbf7f11705cf426a7b2b313a9b44c77d0.
> Revert "Update expected build path"

- resources.txt
Update existing stable branches
Add stable branches for new charms with resources
> Update stable resources

- resources.txt
Add policyd resource for gnocchi
Depends on the following review
https://review.opendev.org/#/c/739274/
> Add policyd resource for gnocchi

- resources.txt
Depends on https://review.opendev.org/#/c/738745/
> Add policyd resource for swift-proxy

- resources.txt
Depends on on https://review.opendev.org/#/c/739275/
> Add policyd resource for aodh

- _charms-git-diff
- _update-requirements
- check-series
- commit-message-2008-groovy.txt
- do-batch
* Addition of charms-git-diff to see what's been changed
* style fixes to _update_requirements
* Removal of accidentally added commit message text.
* Fix to check_series
* Fix to do-batch
> Updates from the freeze batches

- resources.txt
Add in missing kerberos resource for stable branch.
> Add in kerberos as it does have a stable/20.08 release

- build-charm
- push-and-release
The charm pusher was incorrectly pushing the source charm for
operator charms.
> Fix pushing operator charms

- global/classic-amulet/tox.ini
- global/classic-zaza/tox.ini
- global/source-zaza/tox.ini
Discussed here: https://review.opendev.org/#/c/744690/
> Add W504 to flake8's ignore list

- charms.txt
- source-charms.txt
I think this can wait after release freeze
> Add ironic charms

- build-charm
This reverts commit 5e6badb3c572e31740b5bafa7f41c1251cc8380c.
> Revert "Fix EXPECTED_BUILD_DIR for charm-tools 2.8"

- _do-amend-review
- _do-reset-hard-branch
- _ensure_master_libraries_all_charms
- _ensure_reactive_charms_master_libraries
Add a couple of useful tools:
- _do-amend-review $topic
- _do-reset-hard-branch $branch
Fixes to:
- _ensure_master_libraries_all_charms
- _ensure_reactive_charms_master_libraries
> Fixes to tools after 21-04 release

- charms.txt
- source-charms.txt
See https://review.opendev.org/c/openstack/charm-guide/+/796639
> Deprecate charm-barbican-softhsm

- global/source-zaza/test-requirements.txt
This will unblock https://review.opendev.org/c/openstack/charm-keystone-saml-mellon/+/794508
> Pin cryptography to fix keystone-saml-mellon's build

- global/classic-zaza/requirements.txt
- global/classic-zaza/test-requirements.txt
- global/classic-zaza/tox.ini
- global/source-zaza/requirements.txt
- global/source-zaza/src/test-requirements.txt
- global/source-zaza/test-requirements.txt
- global/source-zaza/tox.ini
Closes #151
Validated here: https://review.opendev.org/c/openstack/charm-glance/+/801635
> Fix ResolutionImpossible on tox invocation

- charms.txt
- source-charms.txt
This PR adds the [cinder-lvm](https://opendev.org/openstack/charm-cinder-lvm) charm to the pertinent files.
> Add the subordinate charm cinder-lvm

- lp-builder-config/misc.yaml
- update-channel-single.py
This is so we can pick, say, master git branch, and ignore 'latest'
track.
> Add ignore-track option to be able to ignore a track

- update-channel-single.py
A few more fixes for the ignore track.
> Add ignore track

- lp-builder-config/openstack.yaml
- Add back in barbican-vault
- Correct designate spelling.
- Add back in manila-generic testing charm
> Updates to lp-config

- global/classic-zaza/tox.ini
- global/source-zaza/tox.ini
Allow proxy related environment variables to be passed via tox.
> Pass env vars *_proxy

- update-channel-single.py
As per title, removing superfluous code.
> Remove default setLevel() as its immediately overwritten

- global/classic-zaza/test-requirements.txt
Reflecting recent changes to the template
https://review.opendev.org/q/projects:openstack/charm-+%2522Pin+tempest+for+python%253C3.8%2522
> Pin tempest for python<3.8

- lp-builder-config/misc.yaml
The 1.7 recipe got changed to 1.5 by accident recently.  Change it back.
> Fix vault recipes

- fetch-charms.py
The logic was broken which resulted in an endless loop when trying to select a gerrit review when the topic is the same.
> A small fix to fetch-charms.py when matching multiple reviews

- lp-builder-config/openstack.yaml
Add zed to the following charms:
- barbican
- octavia
- octavia-ashboard
- octavia-diskimage-retrofit
> Add missing zed recipe definitions.

- add-new-release-batch
- add-new-release-single
When adding a new release also update the metadata.yaml with the new ubuntu series.
> Add metadata updates

- _update-requirements
- _update-tox-files
- global/README.md
- global/ops-unknown/requirements.txt
- global/ops-unknown/test-requirements.txt
- global/ops-unknown/tox.ini
- global/ops-unknown/upper-constraints.txt
Create tox, requirements, test-requirements for sunbeam charms
Update scripts to handle new charm structure ops-unknown
> Update global files for sunbeam charms

- tox.ini
use case:
tox -e venv -- python3 fetch-charms.py ...
> Add venv tox target

- global/classic-zaza/tox.ini
- global/ops-unknown/tox.ini
- global/ops-zaza/tox.ini
- global/source-zaza/tox-binary-wheels.ini
- global/source-zaza/tox-source-wheels.ini
Ensure testing with cover works with all charm types.
> Fix coverage targets
