openstack-charmers/release-tools

push-and-publish-multi-series
In preparation for the switch to series in metadata across
all OpenStack charms, update the charm store pusher to auto
detect series in metadata, and publish charms using the multi
target, allowing the charm store to figure out which series
a charm should support.
If detected, this is preferred over any configuration files
in release-tools.
=> Auto-detect series in metadata support

stable-branch-updates
Some .gitreview files do not have an EOF/newline at the end of the last line causing a problem with the addition here on line 17
=> Add carriage return to defaultbranch in .gitreview

commit-message-tests-yaml.template, update-tests-yaml-files
This tool will generate a dynamic commit message from a list of comma separated key:value pairs specified, syntax is:
./update-tests-yaml-files master --amend --noreview --kvs key1:value, key2:value, key3:value
--kvs must be the last parameter
=> adding tool to update key:value pairs in tests.yaml

global/classic-charms/tox.ini, global/source-charms/tox.ini
Some of the available checks are disabled by default, like:
[H106] Don’t put vim configuration in source files
[H203] Use assertIs(Not)None to check for None
=> Enable some off-by-default checks

bug-link-overrides.txt
The vault bug link incorrectly points to
https://bugs.launchpad.net/charm-vault/+filebug
when it should be
https://bugs.launchpad.net/vault-charm/+filebug
Update the bug-link-overrides for vault.
=> Override the vault bug link

.gitignore, commit-message-testr.txt, replace-ostestr-with-stestr
Takes care of a failure in all of our tests, after a system upgrade.
=> Added replace-ostestr-with-stestr

build-charm
There have been a lot of test failures recently in OSCI
because of failures to fetch resources in `charm-build`,
this adds 2 additional tries to finish the task
=> Add a bit of retry logic around `charm-build`

resources.txt
Charm has three resources, these need to be set to zero sized files to enable release publishing.
=> Add resources for keystone-saml-mellon

global/source-zaza/requirements.txt
importlib-resources 1.1.0 removed Python 3.5 support
=> Pin importlib-resources

resources.txt
Recently, the mysql-innodb-cluster charm has added a resource for the
mysql-shell resource (a snap).  In order for the pusher to work, an
entry is required for the master branch.  On release, a stable branch
entry will also be needed.
=> Add mysql-innodb-cluster 0-bytes resource

stable-branch-updates
When using the cs:$CHARM we run into promulgated vs unpromulgated
problems for testing. By using the cs:~openstack-charmers/$CHARM we
avoid this problem.
=> Use the cs:~openstack-charmers charms for stable

README.md, check-repo-links, get-charms, push-and-release, release-stable-charms, repo-link-overrides.txt, update-stable-charms
This shifts to use opendev.org instead of github.com, and adds a repo link check tool, and allows /x/ or /openstack/ urls without having to do local hacks.
=> Use opendev and enable repo link overrides

.gitignore, commit-message-update-branches.txt, release-stable-charms, stable-branch-updates
Add stable charm-helpers to reactive wheelhouse
Use top level project name for non-openstack charms in gerrit
=> 20.05 fixes

global/classic-zaza/requirements.txt
https://bugs.launchpad.net/layer-openstack/+bug/1888225
CI runs: https://review.opendev.org/741934
=> Fix installing dnspython on python 3.5

global/classic-amulet/tox.ini, global/classic-zaza/tox.ini, global/source-zaza/tox.ini
The current PEP8/black coding standard [1] is to place binary operators
on the continuation line at the beginning.  Although charms are not
strictly black compliant, this is a useful direction to head in.
[1]: https://github.com/psf/black/blob/9b484d1bcc2e15dcd5544cddab729c76b4d1d2e9/README.md#line-length
=> Add W503 to ignores for flake8

build-charm
Add support for building ops charmcraft charms. build-charm was
refactored to try and make the code path for two different sorts
of build charm cleaner while maintaining a single script for
building.
=> Add support for building ops charmcraft charms

list-revisions-in-charmstore.py, requirements.txt, tox.ini
This handy tool (tox -e revisions -- &lt;charm-name&gt;) is to enable listing
the dates of revisions of a charm in the charmstore.  e.g. it can be
used to find the first and last versions during a particular stable
series.
It's a bit buggy with some charms (wants you to login repeatedly) but that's more a function of the underlying libraries which haven't been updated in a while.  It probably needs rewriting with request and hitting the API directly, as we only want to read data, and thus shouldn't need to be authorised.
=> Add a simple list-revisions and dates helper

global/classic-zaza/test-requirements.txt, global/source-zaza/test-requirements.txt
The current pin of flake8 makes it not check anything and return
success when executed on Python 3.8 or newer (which means Focal
and onwards, in other words the current LTS).
=> Unpin flake8 for test-requirements

push-and-release
Previous commit f255208bd4 assumed that 'charm push' supported
.charm files. Unfortunately it does not so point at the exploded
directory.
=> Fix charm pusher for operator charms

push-and-release
Due to a recent change the pusher was failing for classic charms
because the built_charm var was unset.
=> Fix classic charm push failure

global/classic-zaza/test-requirements.txt
Need croniter to check test rabbitmq queue stats file. This is pulled
in from the repos on charm install, but we need to pull it in for the
unit tests here as well. Also cf. change
I60141397f39e3b1b0274230db8d984934c98a08d
=> Add croniter dependency for rabbitmq testing

do-batch, global/classic-zaza/test-requirements.txt
Also fix typo
charm-glance needs tempest in its `test-requirements.txt`:
- https://opendev.org/openstack/charm-glance/src/branch/master/test-requirements.txt#L20
- https://opendev.org/openstack/charm-glance/src/branch/master/tests/tests.yaml#L46
Removing it leads to the [following error](https://openstack-ci-reports.ubuntu.com/artifacts/test_charm_pipeline_func_smoke/openstack/charm-glance/761556/2/20298/consoleText.test_charm_func_smoke_20053.txt):
```
Traceback (most recent call last):
File "/tmp/tmp.al4N58v8Mn/func-smoke/bin/functest-run-suite", line 8, in <module>
sys.exit(main())
File "/tmp/tmp.al4N58v8Mn/func-smoke/lib/python3.5/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 278, in main
test_directory=args.test_directory)
File …
```
=> Add tempest to test-requirements.txt for charm-glance

global/classic-amulet/tox.ini, global/classic-zaza/requirements.txt, global/classic-zaza/test-requirements.txt, global/classic-zaza/tox.ini, global/source-amulet/src/tox.ini, global/source-zaza/requirements.txt, global/source-zaza/src/tox.ini, global/source-zaza/test-requirements.txt
Also removing from requirements.txt what was already in
test-requirements.txt
pip 20.3 just got released with a new default resolver
which turned out to be problematic. Also pip 21 will drop
support for python 3.5 soon anyway.
=> Pin pip < 20.3

global/classic-amulet/tox.ini, global/classic-zaza/test-requirements.txt, global/classic-zaza/tox.ini, global/source-amulet/src/tox.ini, global/source-zaza/requirements.txt, global/source-zaza/src/test-requirements.txt, global/source-zaza/src/tox.ini, global/source-zaza/test-requirements.txt
Similar change was done in other *requirements.txt files
in this repo but this one was missed.
Without this change we get
```
09:43:39 py35 installdeps: -r/var/lib/jenkins/checkout/6/ceph-fs/test-requirements.txt
09:44:10 py35 installed: You are using pip version 8.1.1, however version 20.3.1 is available.,You should consider upgrading via the 'pip install --upgrade pip' command.,certifi==2020.11.8,cffi==1.14.4,chardet==3.0.4,charmhelpers==0.20.19,charms.openstack==0.0.1.dev1,charms.reactive==1.3.2,cliff==2.18.0,cmd2==0.8.9,coverage==5.3,cryptography==3.2.1,extras==1.0.0,fixtures==3.0.0,flake8==3.8.4,future==0.18.2,hvac==0.10.5,idna==2.10,importlib-metadata==2.1.1,importlib-resources==3.3.0,Jinja2==2.11.2,linecache2==1.0.0,lxml==4.6.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==3.0.5,netaddr==0. …
```
=> Fix "ImportError: cannot import name 'resources'"

global/classic-zaza/test-requirements.txt, global/source-zaza/test-requirements.txt
Examples of such spurious failures:
- `stevedore`
- https://review.opendev.org/c/openstack/charm-neutron-gateway/+/766595
- https://zuul.opendev.org/t/openstack/build/bae9626ee0794c789f714bce6fedc8a9
- `osprofiler`
- https://review.opendev.org/c/openstack/charm-nova-compute/+/766599
- https://zuul.opendev.org/t/openstack/build/a7cff4a71bb147a8b41a50186c446cf2
- `tempest`
- https://review.opendev.org/c/openstack/charm-ceilometer/+/766555
- https://zuul.opendev.org/t/openstack/build/dd4365dea0da4c91a8fef607cf9df059
=> Fix spurious Zuul failures on Python 3.5

stable-branch-updates
For all layer charms update charms.openstack and charm-helpers to stable
branches. Use sed rather than adding a line which will allow for charms
that do not need charms.openstack.
Update zaza and zaza-openstack-tests to stable.
=> Set stable charms.openstack charm-helpers and zaza

build-charm, global/source-zaza/requirements.txt, global/source-zaza/tox.ini
This PR pins charm-tools to 2.8.3 for the reactive builds for the 21.04
development cycle.  The tox.ini is modified to keep the builds in the
build/builds/<charm>  directory as this has been 'fixed' in 2.8.2+ to
build/<charm>.  In order to keep the release tooling consistent between
the stable and master branches the build/builds/<charm> option is used.
=> Pin charm-tools (for build) to 2.8.3 for 21.04 cycle

_charms-git-diff
Before this change, the script was showing only unstaged
git changes.
=> Improve _charms-git-diff

_do-actual-builds, _do-batch-add-build-lock-file, _do-batch-flip-master-libs-to-stable, _do-clean-reactive, _update-metadata.py, add-build-lock-file, do-batch, flip-master-libs-to-stable, global/source-zaza/tox.ini, requirements.txt
The reproducible charms feature requires building the charms with an
additional option.  This then introduces a build.lock file which is then
used to produce reproducible charms.
This set of commits is to provide the tooling in release tools to update master branch charms (which do not use reproducible builds) into a stable set that does use reproducible builds.
=> Updates to support reproducible charms

_ensure_master_libraries_all_charms
The "interim" release policy had stable/yy.mm branches for
charm-helpers, charms.openstack, charms.ceph, zaza and
zaza-openstack-tests referenced in various requirements files on the
master branch.  These need to be flipped back to master once release is
done.
=> Add helper to flip all charms back to master on master branch

update-charms-metadata
Without this fix:
```
$ ./update-charms-metadata add groovy
...
Command 'add' requires at least 1 argument
usage: _update-metadata.py [list | add | remove | ensure] [<series, ...]
```
=> Fix update-charms-metadata arg parsing

global/classic-zaza/tox.ini, global/source-zaza/src/tox.ini
The patch bumps min version of tox to 3.18.0 in order to
replace tox's whitelist_externals by allowlist_externals option:
https://github.com/tox-dev/tox/blob/master/docs/changelog.rst#v3180-2020-07-23
Co-Authored-By: likui <likui@yovole.com>
Copied from and validated in https://review.opendev.org/c/openstack/charm-ceph-mon/+/803910
=> Change minversion in tox to 3.18.0

_update-tox-files
This change fixes the copy of pip.sh which was using tox.ini as the
source file instead of pip.sh.
=> Fix copy of pip.sh

_do-batch-cp-stable-candidate, push-and-release
This fixes push-and-release so that it does a charm grant for the
channel, as apparently the charmstore has to have the channel version
granted.
The 2nd part is a helper script to copy the current stable channel charm
to the candidate release channel (and grant it).  This is to provide a
'starting' point so that charm pull <charm> --channel=candidate has
something to work with.  It would appear that the charmstore randomly
will not provide a charm if a channel is provided that hasn't been
pushed to (which kind of means 'auto-promotion' to a more stable version
doesn't work.)
=> Fix push-and-release and add stable -> candidate copier

global/classic-zaza/test-requirements.txt, global/classic-zaza/tox.ini, global/source-zaza/tox.ini
This patch reverts "Add psutil to test-requirements for ceilometer" and
adds py39 tox targets.
The test-requirements.txt change is not needed since requirements.txt
already specifies psutil. Instead, py39 tox targets are needed that depend
on the correct requirements file(s).
This reverts commit f6c264ad3cc779e4abf84e1f5a423e73df2320ac.
=> Add py39 tox.ini targets

lp-builder-config/ceph.yaml, lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml, lp-builder-config/ovn.yaml
These are the config yaml files to create and maintain the recipes in
launchpad that will mirror git repos and create builders to build the
charms (using charmcraft) and push them to the charmhub.
Note that they were created be @wolson, and just being uploaded by me.
=> Add launchpad builder configs for charms

global/classic-zaza/charmcraft.yaml, global/source-zaza/charmcraft.yaml
These are the default charmcraft.yaml files for charmcraft to build
classic and reactive charms using the appropriate plugins.
=> Add charmcraft yaml templates for reactive/classic charms

lp-builder-config/openstack.yaml
Typos:
* charm-glance-simplestreams-sync repo URL
* charm-keystone-ldap had wrong repo URL
Disable two charms as they are being used for testing prior to charmhub
migration switchover.
* charm-manila-generic
* charm-neutron-dynamic-routing
=> Fix typos and disable two test charms

update-channel-single.py
The lp-builder-config yaml files provide git branch -> charmhub
track/channel mappings for the builder config.  This patch updates the
update-channel-single.py tool with an option to provide branches instead
of channels, and then the appropriate charmhub track/channel will be
used for the charm in the bundle.  This is to automate handling of the
charms tests bundle updates.
=> Update update-channel-single.py to work with lp-config

global/source-zaza/build-requirements.txt, global/source-zaza/charmcraft.yaml, global/source-zaza/rename.sh, global/source-zaza/test-requirements.txt, global/source-zaza/tox.ini
This patch to the global/source-zaza files is to enable a reactive charm
to be built by the CI system in the 'charm-build' job. This is so that
the charm will have to "charmcraft build" before doing tests and ensures
that it is at least buildable prior to being delivered to launchpad for
build and push to the charmhub.
=> Updates to global files for reactive charms, charmcraft and charmhub

lp-builder-config/misc.yaml
The bionic track was errantly included in the charmhub launchpad
configuration. This removes the bionic track, since only focal is
supported in the charm.
=> Remove bionic from mysql-innodb-cluster lp config

lp-builder-config/openstack.yaml
Scope the ironic tracks and branches to Train+, as that's all the charm
supports.
=> Scope ironic tracks and branches correctly

lp-builder-config/openstack.yaml
Scope the magnum tracks and branches to Ussuri+, as that is all the
charm supports.
=> Scope magnum tracks and branches correctly

lp-builder-config/ceph.yaml
Ceph dashboard only supports octopus and newer. Let's scope it correctly
in the lp-builder-config tools.
=> Scope ceph-dashboard to Octopus and newer

code-imports-status.py
This program checks the status of the code imports for the charms
defined in the lp-builder-config yaml files, it will clone the upstream
repository and compare against the mirror to find missing commits.
Steps:
- check code import review status
- git clone the upstream repository
- add a remote using LP's url
- run git fetch for each of the remotes
- iterate the branches and for each branch compare head against the lp
mirror head.
The program supports to filter the list of charms by category
(openstack, misc, ceph, ovn) or give an explicit list of charms (e.g.
--charm nova-compute --charm keystone).
Usage example:
$ python3 code-imports-status.py  --charm nova-compute
charm-nova-compute Failed (29 days ago) https://code.launchpad.net/~openstack-charmers/charm-nova-compute/+git/charm-nova- …
=> Add code-imports-status.py

lp-builder-config/ovn.yaml
The main branch is currently tracking OVN 22.03 which is also the
version going into Ubuntu Jammy.
=> Add ovn 22.03 track

lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml
The openstack-loadbalancer isn't actually an openstack service, but is
instead a loadbalancer for openstack projects.  As such, it's more like
rabbitmq-server or mysql-innodb-cluster and will have 'focal' and
'jammy' releases, that are aligned to the LTS releases that it runs on.
This PR moves them.  Note, this will affect upstream branches and tracks
on charmhub.
=> Move openstack-loadbalancer to the misc section

global/classic-zaza/requirements.txt, global/source-zaza/requirements.txt
cryptography>=3.4 requires a rust compiler.
=> Pin cryptography<3.4

update-channel-single.py
The `--bundle` argument allows the user to give a specific file to be
processed by update-channel-single.py, it can be used multiple times to
pass multiple files.
=> update-channel-single.py: Add --bundle argument.

lp-builder-config/ceph.yaml, lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml, lp-builder-config/ovn.yaml
charmcraft 1.6 renamed the environment variable from CHARMCRAFT_STAGE to
CRAFT_STAGE breaking charms building.
https://github.com/canonical/craft-parts/commit/6c18447497897794dc9ea86f164fb21c035f12d1
=> Pin charmcraft to 1.5/stable

update-channel-single.py
Read the list of charms from lp-builder-config/*.yaml since charms.txt
and operator-charms.txt were removed.
=> update-channel-single.py: Use lp-builder-config instead of charms.txt

lp-builder-config/ceph.yaml, lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml, lp-builder-config/ovn.yaml
This is mainly moving channels to the stable/yoga, stable/22.04
and stable/quincy tracks for openstack, ovn and ceph charms.  The
misc charms are handled a little differently, in that charms need to
span two LTS (for series upgrade), but also try to track the major
version number of the payload.
=> Changes to lp-builder-config for 22.04 release

lp-builder-config/ceph.yaml, lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml, lp-builder-config/ovn.yaml
This is inline with the current policy where a stable backport receives
two +2s on Gerrit and then is immediately pushed to the stable branch.
The stable branches are:
- yoga/stable
- quincy/stable
- 22.03/stable
- various for the misc charms (see patch)
Also, added an 'enabled: False' key for branches that have not yet been
enabled so that the tool can ignore them unless they are specifically
mentioned.
=> Switch recent stable releases to <track>/stable

global/source-zaza/charmcraft-build-lock-file.yaml
This 'generic' charmcraft.yaml is used to create build.lock files, and
the additional library (libpq-dev) is required for the vault charm as
part of the build process.
=> Add libpq-dev to the charmcraft-build-lock-file.yaml

global/classic-zaza/tox.ini, global/source-zaza/requirements.txt, global/source-zaza/tox.ini
charm-tools gained support for python 3.10 in master[0] and most
importantly the pinning of dependencies were lifted which allows the
correct installation of packages like ruamel.yaml.
[0] https://github.com/juju/charm-tools/pull/614
=> Use charm-tools from the git repo.

lp-builder-config/misc.yaml
As we've learned, going down to a minor version number is less than
ideal for channel names when pulling from the archives. This changes
the channel name for mysql-innodb-cluster and mysql-router from 8.0.19
to 8.0.
=> Update mysql channel names to 8.0

lp-builder-config/ceph.yaml, lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml, lp-builder-config/ovn.yaml, lp-builder-config/trilio.yaml
Switch from 1.5/stable to 1.7/stable to get 22.04 support.
=> Pin charmcraft to 1.7/stable

global/classic-zaza/tox.ini, global/source-zaza/tox.ini
charmcraft 2.0 dropped the 'build' target in favor of 'pack' which
was deprecated in 1.5[0].
[0] https://juju.is/docs/sdk/charmcraft-deprecations#heading--dn06
=> Use 'charmcraft pack'

lp-builder-config/ceph.yaml, lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml, lp-builder-config/ovn.yaml
Update the channel targets for the OpenStack, Ceph and OVN charms
following the Xena stable (and associated charms, releases)
=> [xena|pacific|21.09]/stable release

lp-builder-config/openstack.yaml
Register keystone-openidc in lp-builder-config. The only branch that exists at the moment is master, hence latest/edge track/risk is defined.
=> Add keystone-openidc

lp-builder-config/misc.yaml
The charm openidc-test-fixture is meant to be used for testing keystone-openidc charm.
=> Add openidc-test-fixture to lp-builder-config

add-new-release-batch, add-new-release-single, fetch-charms-for-master, global/classic-zaza/.zuul.yaml, global/classic-zaza/charmcraft.yaml, global/classic-zaza/requirements.txt, global/classic-zaza/test-requirements.txt, global/classic-zaza/tox.ini, global/source-zaza/.zuul.yaml, global/source-zaza/charmcraft.yaml, global/source-zaza/requirements.txt, global/source-zaza/test-requirements.txt, global/source-zaza/tox.ini, lp-builder-config/ceph.yaml, lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml, lp-builder-config/ovn.yaml, lp-builder-config/trilio.yaml
* fetch-charms-for-master: Fetch charms based on lp-builder-config
(based on charmhub-migration/fetch-charms-for.sh)
* add-new-release-tests-batch, add-new-release-tests-single: Add new
release bundles and update tests.yaml, osci.yaml, and .zuul.yaml
* add zed jobs to global .zuul.yaml
=> New scripts for adding new release tests

lp-builder-config/openstack.yaml
The commit 09890e81 introduced an entry for cinder-purestorage that lists explicitly the git branches that need to be used to create recipes, making this entry obsolete.
=> Drop duplicated entry of cinder-purestorage

lp-builder-config/openstack.yaml
queens to stein is supported on the train track, so this PR comments out those channels. Switched enabled to True for all the channels (although this feature is not quite ready in charmhub-lp-tools).
=> Update the openstack release channels to remove queens -> stein

lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml
Move the pacemaker-remote charm configuration to the misc section as it doesn't follow the OpenStack charms' release names, but is instead distro specific.
=> Move the pacemaker-remote charm to the misc section

lp-builder-config/openstack.yaml
Some charms erroneously describe tracks for queens, but these charms were never released on queens.  Remove queens and adjust tracks as necessary.
=> Correct stable channels for various OpenStack charms

get-build-lock, lp-builder-config/openstack.yaml, set-zed-bundles, shell-into, stable-branch-updates, update-channel-single.py
These updates were done to help with working with the release-tools during the stable/zed branch cuts and first commits.  They are:
* get-build-lock - extract a build.lock file from a LXD container that was used to write the lock-file.
* shell-into - helper script to shell into an LXD container using the charm name.  Useful to get into the container to actually run `charm build --write-lock-file .` in the /root/parts/charm/src directory.
* set-zed-bundles - the script used to write the modifications to the bundles for the stable/zed branch of each charm.
* update-channel-single.py - modification to ensure that the 'edge' risk can be selected regardless of what the lp-build-config is configured as a channel mapping for a branch of a charm.
* lp-builder-config/openstack.yaml - modifications …
=> Updates to release-tools during the zed stable/branch cuts

global/classic-zaza/tox.ini, global/source-zaza/tox.ini
Make the implicit information explicit,
regarding why charmcraft clean is used in the default build target,
and a suggestion for rebuilding faster if necessary.
ref https://github.com/openstack-charmers/release-tools/pull/250#pullrequestreview-1142586794
=> Add informational comments to tox build target

lp-builder-config/openstack.yaml
The octavia-diskimage-retrofit charmcraft for yoga now requires 2.0/stable so bump this in the config.
=> Bump charmcraft to 2.0 for diskimage-retrofit charm

lp-builder-config/ceph.yaml
This enables stable/quincy.2 to push to quincy/edge.  The existing stable/quincy branch continues to push to quincy/stable.
=> Add stable/quincy.2 recipe for quincy/edge

lp-builder-config/misc.yaml
The mysql-router charm, at the moment, uses charmcraft 1.5 for its
building, their charmcraft.yaml[0] relies on the environment variables
$CHARMCRAFT_* that were dropped after 1.5
[0] https://opendev.org/openstack/charm-mysql-router/src/branch/master/charmcraft.yaml#L14
=> Use charmcraft 1.5 in mysql-router master

lp-builder-config/ovn.yaml
ovn 22.09 release uses charmcraft 2.1 and a branch named stable/22.09
=> Add ovn 22.09

global/classic-zaza/tox.ini, global/source-zaza/tox.ini
Running `charmcraft clean` at the end of the `build` target prevents
from littering the system with containers that won't be reused since
before running `charmcraft pack` the command `charmcraft clean` is
executed.
=> Clean after building a charm.

release-contributors.sh
The release-contributors.sh script prints the list of contributors in alphabetical order using "git log" and a baseline branch to compare against master
Usage example of contributors to the Ceph, OVN and OpenStack charms since Quincy, 22.03 and Yoga releases respectively.
./release-contributors.sh \
--os-baseline yoga \
--ovn-baseline 22.03 \
--ceph-baseline quincy \
--libs-dir ./git/openstack-charms
Co-Authored-By: Peter Matulis <peter.matulis@canonical.com>
=> Script to collect contributors statistics.

do-batch-with-cmd, global/classic-zaza/build-requirements.txt, lp-builder-config/ceph.yaml, lp-builder-config/misc.yaml, lp-builder-config/openstack.yaml, lp-builder-config/ovn.yaml, lp-builder-config/trilio.yaml
This addition enables the charmhub-lp-tools command to read the config and apply the bases automatically for channels.  This information is separate from the charmcraft.yaml as channels can contain charms from different eras and it's important that they are maintained.
=> Add bases to the builder config

lp-builder-config/ceph.yaml, lp-builder-config/misc.yaml
These updates correspond to updates made in this topic: https://review.opendev.org/q/topic:kinetic-support
I did not update ceph-osd because it already built successfully and is published to latest/edge for 22.10.
=> Misc/ceph lp-builder-config updates for 22.10

fetch-charms.py, requirements.txt
We have a mix of charm repositories with master and main branches. Therefore 'fetch-charms.py --branch master' will fail for some git repos and 'fetch-charms.py --branch main' will do the same.
This change updates fetch-charms.py to treat master and main as alias'. If fetching master fails for a project, try to fetch main. And if fetching main fails for a project, try to fetch master.
=> Treat fetch of master or main as alias'

add-new-release-batch, add-new-release-single
The current code only added multi-arch run-on bases when adding new release support. Update the code to support adding of both multi-arch and single-arch run-on bases.
=> Add single-arch run-on bases

tox.ini
The double dash breaks the execution of the python scripts when passing arguments.
=> Drop `--` from commands

charmhub-branches/.gitignore, charmhub-branches/USAGE.md, charmhub-branches/export-token.sh, charmhub-branches/get-creds.sh, charmhub-branches/list-tracks.sh, charmhub-branches/make-track.sh
These scripts handle the creation of channels in the charmhub for
charms. They are a placeholder until the charmhub-lp-tool is updated to
handle channel creation.
=> Add scripts to handle self-serve channel creation

fetch-charms.py, release-contributors.sh, tox.ini
This new target runs release-contributors.sh, but more importantly is that enables an environment where fetch-charms.py can run successfully
=> Add `release-contributors` tox target

global/classic-zaza/tox.ini, global/ops-zaza/tox.ini, global/source-zaza/tox-binary-wheels.ini, global/source-zaza/tox-source-wheels.ini, lock-with-pip-compile
This will be re-instated for the master/main branches after the 2023.2
release is done.
=> Remove py311 target (for 2023.2) updates.

global/classic-zaza/tox.ini, global/ops-zaza/tox.ini, global/source-zaza/tox-binary-wheels.ini, global/source-zaza/tox-source-wheels.ini
The constraints file allows globally pinning the versions used by the tox testing environments and posibly override this by zosci[0]
[0] https://github.com/openstack-charmers/zosci-config/pull/324
Depends-On: https://github.com/openstack-charmers/zaza-openstack-tests/pull/1184
=> Add constraints to tox.ini files under global/**

global/classic-zaza/tox.ini, global/ops-zaza/tox.ini, global/source-zaza/tox-binary-wheels.ini, global/source-zaza/tox-source-wheels.ini
The environment variable TOX_CONSTRAINTS_FILE is used by upstream zuul to pass OpenStack's global upper constraints, when (re)using this environment variable the unitended consequence is that running CI jobs in upstream's zuul makes the charm to use the wrong constraints file.
=> Rename TOX_CONSTRAINTS_FILE to TEST_CONSTRAINTS_FILE
